export { default as Authorized } from '@/components/Authorized/AuthorizedFgis.vue'
export { default as Captcha } from '@/components/Captcha/CaptchaFgis.vue'
export { default as CookieBanner } from '@/components/CookieBanner/CookieBanner.vue'
export { default as Footer } from '@/components/Footer/FooterFgis.vue'
export { default as Header } from '@/components/Header/HeaderFGIS.vue'
export { Modal, ModalSuccess, ModalError } from '@/components/Modal'
export { default as Popover } from '@/components/Popover/PopoverCustom.vue'
export { default as Sidebar } from '@/components/Sidebar/SidebarFgis.vue'
